# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9eece599c590791818f154ef959e24be2e2040309e37cd679a9c67fb39b23a972b280cb726602cbf5eb00d44f69eeead4563b98e6f56fc04038f83da68adc53

test:
  secret_key_base: d5c14bc57eea0a2de9629b123004cbd95845e0c7ea17233b339608264d4e74f26fb09fe794d97acdc84cbfc7269eeb360be2307f30a5c80db0c21ad1f58f6d82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
